### ISSUE TITLE
NoMethodError: undefined method `extname' for "/.../../asset.gif":String

### ISSUE THREAD

**Issue by lubosch** [appfolio/eslint-rails#24]
Hi,

the newest version has in lib/eslint-rails/runner.rb line 31 `Rails.application.assets.each_file.to_a.select { |pn| pn.extname == '.js' }
 ` .. `Rails.application.assets.each_file.to_a` returns an array of strings, not files, therefore string.extname trhows an error .. any suggestions?

Thanks :)

**Comment by filippovG** [comment]
@lubosch 
I've had a same error on my setup (not sure if it is related to Ruby/Rails version), have a fork for this fix:

gem 'eslint-rails', github: 'filippovG/eslint-rails', branch: 'fix-extname-undefined'

**Comment by jonkessler** [comment]
Hmm.. I'm certain this was working before. I'll fix it.

**Comment by jonkessler** [comment]
Looks like it changed in Rails 4.2. Fixing.

**Comment by jonkessler** [comment]
Released version 1.2.1 with the fix. Thank you for reporting this.

**Comment by lubosch** [comment]
Thank you, everything is working now
