### ISSUE TITLE
how to use airbnb pattern?

### ISSUE THREAD

**Issue by renanol** [appfolio/eslint-rails#27]

**Comment by jonkessler** [comment]
I'm not sure what you're asking. Could you clarify?

**Comment by renanol** [comment]
How I can insert this pattern https://github.com/airbnb/javascript ? With npm is simple, but don't know how to use in eslint-rails.

**Comment by stiller-leser** [comment]
@renanol You've closed the issue, however I am looking for a solution as well. Could you describe yours?
